# Generated by Django 3.0.3 on 2020-02-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EU', 'Euro'), ('USD', 'US dollar.')], max_length=3)),
                ('course_buy', models.IntegerField(max_length=4)),
                ('course_sell', models.IntegerField(max_length=4)),
                ('date_to', models.DateField()),
                ('date_from', models.DateField()),
            ],
        ),
    ]
