# Generated by Django 3.0.3 on 2020-02-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='name',
            field=models.CharField(choices=[('EU', 'EU'), ('USD', 'USD')], max_length=3),
        ),
    ]
