# Generated by Django 3.0.3 on 2020-02-26 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0002_auto_20200226_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='date_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='money',
            name='date_to',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
