# Generated by Django 3.0.3 on 2020-02-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0003_auto_20200226_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='course_buy',
            field=models.FloatField(max_length=4),
        ),
        migrations.AlterField(
            model_name='money',
            name='course_sell',
            field=models.FloatField(max_length=4),
        ),
    ]
